title: The Change Is Overdue
author: Polly K
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A test blog site but also a place for me to rant about things that annoy me lmao

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  pollykuts # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
